---
###############################################################################
# Config
###############################################################################
# Re-run tests when config, or restore is changed.
#
# Tests:
# * Running Postgres server instance.
# * Configuration files with options are rendered appropriately based on type.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        postgres_flg_config: true
        postgres_cfg_users:
          - name: 'example'
            host: 'localhost'
            password: 'example'
            state: 'present'
            append_privs: false
            encrypted: true
            extensions:
              owner:
                - login_db: 'test1'
                  obj_type: 'table'
                - login_db: 'test1'
                  obj_type: 'sequence'
                - login_db: 'test1'
                  obj_type: 'view'
              priv:
                - login_db: 'postgres'
                  privs: 'ALL'
                  type: 'database'
                - login_db: 'test1'
                  privs: 'ALL'
                  type: 'database'
        postgres_cfg_dbs:
          - name: 'test1'
            owner: 'example'
          - name: 'test2'
            owner: 'postgres'
        postgres_srv_conf_d: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/conf.d"
          }}'
        postgres_srv_secure_conf_d: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/secure.conf.d"
          }}'
        postgres_srv_environment: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/main/environment"
          }}'
        postgres_srv_pg_ctl: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/main/pg_ctl.conf"
          }}'
        postgres_srv_pg_hba: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/main/pg_hba.conf"
          }}'
        postgres_srv_pg_ident: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/main/pg_ident.conf"
          }}'
        postgres_srv_postgresql: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/main/postgresql.conf"
          }}'
        postgres_srv_start: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/main/start.conf"
          }}'
        postgres_srv_profile: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/profile.d/postgres"
          }}'
platforms:
  - name: 'postgres-config'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
