---
# yamllint disable rule:line-length
###############################################################################
# Postgres Config
###############################################################################
# Data locations may be mounted over network (with only postgres user and
# everything else mapping to nobody/nogroup). Execute commands touching those
# root mount points as postgres user to ensure they can be read or written.
#
# Postgres will refuse to start with any invalid configuration option, even for
# options that are deprecated (using a new template for an older version) or
# options that don't exist yet (using a current template for a new release).
#
# Default service does not log configuration errors on startup. This must be
# done manually to see what configuration issues are occurring. With a default
# installation location, run:
#
#   su - postgres
#   /usr/lib/postgresql/17/bin/postgres -d 3 \
#   -D /var/lib/postgresql/17/main \
#   -c config_file=/etc/postgresql/17/main/postgresql.conf
#
# Reference:
# * https://www.postgresql.org/docs/current/config-setting.html
# * https://www.postgresql.org/docs/current/config-setting.html#CONFIG-SETTING-NAMES-VALUES
# yamllint enable rule:line-length

- name: '{{ "Config | filesystem | deploy " ~ postgres__etc._conf_d }}'
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ postgres__etc._conf_d }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0644'
  loop:
    '{{ query("community.general.filetree", postgres__srv._conf_d) }}'
  loop_control:
    label: '{{ item.path }}'
  when: item.state == 'file'
  register: postgres__local

- name: 'Config | filesystem | query remote files'
  ansible.builtin.find:
    paths: '{{ postgres__etc._conf_d }}'
    file_type: 'file'
    recurse: true
  register: postgres__remote

- name: 'Config | filesystem | remove unmanaged files'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: 'absent'
  loop: '{{ postgres__remote.files }}'
  loop_control:
    label: '{{ item.path }}'
  when: >
    item.path not in postgres__local.results | selectattr('dest', 'defined') |
    map(attribute='dest') | list

- name: '{{ "Config | filesystem | deploy " ~ postgres__etc._secure_conf_d }}'
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ postgres__etc._secure_conf_d }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0644'
  loop:
    '{{ query("community.general.filetree", postgres__srv._secure_conf_d) }}'
  loop_control:
    label: '{{ item.path }}'
  when: item.state == 'file'
  register: postgres__local

- name: 'Config | filesystem | query remote files'
  ansible.builtin.find:
    paths: '{{ postgres__etc._secure_conf_d }}'
    file_type: 'file'
    recurse: true
  register: postgres__remote

- name: 'Config | filesystem | remove unmanaged files'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: 'absent'
  loop: '{{ postgres__remote.files }}'
  loop_control:
    label: '{{ item.path }}'
  when: >
    item.path not in postgres__local.results | selectattr('dest', 'defined') |
    map(attribute='dest') | list

- name:
    '{{ "Config | filesystem | set " ~ postgres__etc._environment }}'
  when: postgres__etc._environment | length > 0
  ansible.builtin.template:
    src: '{{ postgres__srv._environment }}'
    dest: '{{ postgres__etc._environment }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0644'

- name:
    '{{ "Config | filesystem | set " ~ postgres__etc._pg_ctl }}'
  when: postgres__etc._pg_ctl | length > 0
  ansible.builtin.template:
    src: '{{ postgres__srv._pg_ctl }}'
    dest: '{{ postgres__etc._pg_ctl }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0644'

- name:
    '{{ "Config | filesystem | set " ~ postgres__etc._pg_hba }}'
  when: postgres__etc._pg_hba | length > 0
  ansible.builtin.template:
    src: '{{ postgres__srv._pg_hba }}'
    dest: '{{ postgres__etc._pg_hba }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0640'

- name:
    '{{ "Config | filesystem | set " ~ postgres__etc._pg_ident }}'
  when: postgres__etc._pg_ident | length > 0
  ansible.builtin.template:
    src: '{{ postgres__srv._pg_ident }}'
    dest: '{{ postgres__etc._pg_ident }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0640'

- name:
    '{{ "Config | filesystem | set " ~ postgres__etc._postgresql }}'
  when: postgres__etc._postgresql | length > 0
  ansible.builtin.template:
    src: '{{ postgres__srv._postgresql }}'
    dest: '{{ postgres__etc._postgresql }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0644'

- name:
    '{{ "Config | filesystem | set " ~ postgres__etc._start }}'
  when: postgres__etc._start | length > 0
  ansible.builtin.template:
    src: '{{ postgres__srv._start }}'
    dest: '{{ postgres__etc._start }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0644'
