---
# yamllint disable rule:line-length
###############################################################################
# Postgres Config
###############################################################################
# Data locations may be mounted over network (with only postgres user and
# everything else mapping to nobody/nogroup). Execute commands touching those
# root mount points as postgres user to ensure they can be read or written.
#
# Postgres will refuse to start with any invalid configuration option, even for
# options that are deprecated (using a new template for an older version) or
# options that don't exist yet (using a current template for a new release).
#
# Default service does not log configuration errors on startup. This must be
# done manually to see what configuration issues are occurring. With a default
# installation location, run:
#
#   su - postgres
#   /usr/lib/postgresql/17/bin/postgres -d 3 \
#   -D /var/lib/postgresql/17/main \
#   -c config_file=/etc/postgresql/17/main/postgresql.conf
#
# Reference:
# * https://www.postgresql.org/docs/current/config-setting.html
# * https://www.postgresql.org/docs/current/config-setting.html#CONFIG-SETTING-NAMES-VALUES
# yamllint enable rule:line-length

- name: '{{ "Config | filesystem | set " ~ postgres__etc._conf_d }}'
  when: postgres__srv._conf_d | length > 0
  block:
    - name: 'Config | filetree | set managed directories'
      ansible.builtin.file:
        path: '{{ postgres__etc._conf_d ~ "/" ~ item.path }}'
        owner: '{{ postgres__srv._user }}'
        group: '{{ postgres__srv._group }}'
        mode: '0755'
        state: 'directory'
      loop:
        '{{ query("community.general.filetree", postgres__srv._conf_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'directory'

    - name: 'Config | filetree | set managed files'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ postgres__etc._conf_d ~ "/" ~ item.path }}'
        owner: '{{ postgres__srv._user }}'
        group: '{{ postgres__srv._group }}'
        mode: '0644'
      loop:
        '{{ query("community.general.filetree", postgres__srv._conf_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'file'

    - name: 'Config | filesystem | query remote files'
      ansible.builtin.find:
        paths: '{{ postgres__etc._conf_d }}'
        file_type: 'any'
        hidden: true
        recurse: true
      register: postgres__remote

    - name: 'Config | filetree | remove unmanaged files and directories'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop:
        '{{ postgres__remote.files | sort(attribute="path", reverse=true) }}'
      loop_control:
        label: '{{ item.path }}'
      when: >
        item.path not in
        (
          query("community.general.filetree", postgres__srv._conf_d) |
          map(attribute='path') |
          map('regex_replace', '^', postgres__etc._conf_d ~ "/") | list
        )

- name: '{{ "Config | filesystem | query " ~ postgres__etc._conf_d }}'
  when: postgres__srv._conf_d | length == 0
  ansible.builtin.find:
    paths: "{{ postgres__etc._conf_d }}"
    recurse: false  # Don't need to enumerate sub-directories to remove.
    hidden: true
  register: postgres__cmd

- name: '{{ "Config | filesystem | clear " ~ postgres__etc._conf_d }}'
  when: postgres__srv._conf_d | length == 0
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ postgres__cmd.files }}"

- name: '{{ "Config | filesystem | set " ~ postgres__etc._secure_conf_d }}'
  when: postgres__srv._secure_conf_d | length > 0
  block:
    - name: 'Config | filetree | set managed directories'
      ansible.builtin.file:
        path: '{{ postgres__etc._secure_conf_d ~ "/" ~ item.path }}'
        owner: '{{ postgres__srv._user }}'
        group: '{{ postgres__srv._group }}'
        mode: '0750'
        state: 'directory'
      loop: '{{
          query("community.general.filetree", postgres__srv._secure_conf_d)
        }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'directory'

    - name: 'Config | filetree | set managed files'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ postgres__etc._secure_conf_d ~ "/" ~ item.path }}'
        owner: '{{ postgres__srv._user }}'
        group: '{{ postgres__srv._group }}'
        mode: '0640'
      loop: '{{
          query("community.general.filetree", postgres__srv._secure_conf_d)
        }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'file'

    - name: 'Config | filesystem | query remote files'
      ansible.builtin.find:
        paths: '{{ postgres__etc._secure_conf_d }}'
        file_type: 'any'
        hidden: true
        recurse: true
      register: postgres__remote

    - name: 'Config | filetree | remove unmanaged files and directories'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop:
        '{{ postgres__remote.files | sort(attribute="path", reverse=true) }}'
      loop_control:
        label: '{{ item.path }}'
      when: >
        item.path not in
        (
          query("community.general.filetree", postgres__srv._secure_conf_d) |
          map(attribute='path') |
          map('regex_replace', '^', postgres__etc._secure_conf_d ~ "/") | list
        )

- name: '{{ "Config | filesystem | query " ~ postgres__etc._secure_conf_d }}'
  when: postgres__srv._secure_conf_d | length == 0
  ansible.builtin.find:
    paths: "{{ postgres__etc._secure_conf_d }}"
    recurse: false  # Don't need to enumerate sub-directories to remove.
    hidden: true
  register: postgres__cmd

- name: '{{ "Config | filesystem | clear " ~ postgres__etc._secure_conf_d }}'
  when: postgres__srv._secure_conf_d | length == 0
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ postgres__cmd.files }}"

- name: '{{ "Config | filesystem | set " ~ postgres__etc._environment }}'
  when: postgres__srv._environment | length > 0
  ansible.builtin.template:
    src: '{{ postgres__srv._environment }}'
    dest: '{{ postgres__etc._environment }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0644'

- name:
    '{{ "Config | filesystem | set " ~ postgres__etc._pg_ctl }}'
  when: postgres__srv._pg_ctl | length > 0
  ansible.builtin.template:
    src: '{{ postgres__srv._pg_ctl }}'
    dest: '{{ postgres__etc._pg_ctl }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0644'

- name:
    '{{ "Config | filesystem | set " ~ postgres__etc._pg_hba }}'
  when: postgres__srv._pg_hba | length > 0
  ansible.builtin.template:
    src: '{{ postgres__srv._pg_hba }}'
    dest: '{{ postgres__etc._pg_hba }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0640'

- name:
    '{{ "Config | filesystem | set " ~ postgres__etc._pg_ident }}'
  when: postgres__srv._pg_ident | length > 0
  ansible.builtin.template:
    src: '{{ postgres__srv._pg_ident }}'
    dest: '{{ postgres__etc._pg_ident }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0640'

- name:
    '{{ "Config | filesystem | set " ~ postgres__etc._postgresql }}'
  when: postgres__srv._postgresql | length > 0
  ansible.builtin.template:
    src: '{{ postgres__srv._postgresql }}'
    dest: '{{ postgres__etc._postgresql }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0644'

- name:
    '{{ "Config | filesystem | set " ~ postgres__etc._start }}'
  when: postgres__srv._start | length > 0
  ansible.builtin.template:
    src: '{{ postgres__srv._start }}'
    dest: '{{ postgres__etc._start }}'
    owner: '{{ postgres__srv._user }}'
    group: '{{ postgres__srv._group }}'
    mode: '0644'
