---
# yamllint disable rule:line-length
###############################################################################
# Manage User Extensions.
###############################################################################
# Imported DB's need to have permissions re-propagated. Use psql command line
# if user option is defined, otherwise depend on user configuring permissions
# correctly via owner and priv extensions.
#
# This allows for more granular controller of user permissions by the role
# consumer.
#
# Use DB connection options specified in the DB object, defaulting to
# postgres_srv_connection options for connection only options if needed:
# * ca_cert
# * connect_params
# * login_host
# * login_password
# * login_port
# * login_unix_socket
# * login_user
# * session_role
# * ssl_cert
# * ssl_key
# * ssl_mode
#
# Args:
#   user: dict - user from postgres_cfg_users.
#
# Reference:
# * https://github.com/ansible/ansible/issues/29774
# * https://semisignal.com/postgresql-database-import-with-ansible/
# * https://stackoverflow.com/questions/1348126/modify-owner-on-all-tables-simultaneously-in-postgresql
# yamllint enable rule:line-length

- name: 'Manage | extensions | database_owner'
  when: user.extensions.database_owner is defined
  ansible.builtin.command:
    argv:
      - '{{ postgres__etc._owner_script }}'
      - '{{ item }}'
      - '{{ user.name }}'
  register: postgres__owner_script
  failed_when: postgres__owner_script.rc != 0
  changed_when: true
  become: true
  become_user: '{{ postgres__srv._user }}'
  loop: '{{ user.extensions.database_owner }}'

- name: 'Manage | extensions | owner'
  when: user.extensions.owner is defined
  community.postgresql.postgresql_owner:
    ca_cert: '{{ (

          user.ca_cert
          if user.ca_cert is defined else
          postgres__srv._connection.ca_cert
        ) | default(omit)
      }}'
    connect_params: '{{ (

          user.connect_params
          if user.connect_params is defined else
          postgres__srv._connection.connect_params
        ) | default({})
      }}'
    fail_on_role: '{{ owner.fail_on_role | default(omit) }}'
    login_db: '{{ (

          owner.login_db
          if owner.login_db is defined else
          user.login_db
        ) | default(omit)
      }}'
    login_host: '{{ (

          user.login_host
          if user.login_host is defined else
          postgres__srv._connection.login_host
        ) | default(postgres__cfg._login_host)
      }}'
    login_password: '{{ (

          user.login_password
          if user.login_password is defined else
          postgres__srv._connection.login_password
        ) | default(omit)
      }}'
    login_port: '{{ (

          user.login_port
          if user.login_port is defined else
          postgres__srv._connection.login_port
        ) | default(postgres__cfg._port)
      }}'
    login_unix_socket: '{{ (

          user.login_unix_socket
          if user.login_unix_socket is defined else
          postgres__srv._connection.login_unix_socket
        ) | default(postgres__cfg._socket_d)
      }}'
    login_user: '{{ (

          user.login_user
          if user.login_user is defined else
          postgres__srv._connection.login_user
        ) | default(postgres__cfg._login_user)
      }}'
    new_owner:
      '{{ owner.new_owner if owner.new_owner is defined else user.name }}'
    obj_name: '{{ owner.obj_name | default(omit) }}'
    obj_type: '{{ owner.obj_type | default(omit) }}'
    reassign_owned_by: '{{ owner.reassign_owned_by | default(omit) }}'
    session_role: '{{ (

          user.session_role
          if user.session_role is defined else
          postgres__srv._connection.session_role
        ) | default(omit)
      }}'
    ssl_cert: '{{ (

          user.ssl_cert
          if user.ssl_cert is defined else
          postgres__srv._connection.ssl_cert
        ) | default(omit)
      }}'
    ssl_key: '{{ (

          user.ssl_key
          if user.ssl_key is defined else
          postgres__srv._connection.ssl_key
        ) | default(omit)
      }}'
    ssl_mode: '{{ (

          user.ssl_mode
          if user.ssl_mode is defined else
          postgres__srv._connection.ssl_mode
        ) | default("prefer")
      }}'
    trust_input: '{{ user.trust_input | default(true) }}'
  become: true
  become_user: '{{ postgres__srv._user }}'
  loop: '{{ user.extensions.owner }}'
  loop_control:
    loop_var: 'owner'
    label: '{{
        owner.login_db ~ " " ~
        owner.new_owner | default(user.name) ~ ":" ~
        owner.obj_name | default("") ~ " " ~
        owner.obj_type | default("") ~ " " ~
        owner.reassign_owned_by | default("")
      }}'

- name: 'Manage | extensions | priv'
  when: user.extensions.priv is defined
  community.postgresql.postgresql_privs:
    ca_cert: '{{ (

          user.ca_cert
          if user.ca_cert is defined else
          postgres__srv._connection.ca_cert
        ) | default(omit)
      }}'
    connect_params: '{{ (

          user.connect_params
          if user.connect_params is defined else
          postgres__srv._connection.connect_params
        ) | default({})
      }}'
    fail_on_role: '{{ user.fail_on_user | default(true) }}'
    grant_option: '{{ priv.grant_option | default(omit) }}'
    login_db: '{{ (

          priv.login_db
          if priv.login_db is defined else
          user.login_db
        ) | default(omit)
      }}'
    login_host: '{{ (

          user.login_host
          if user.login_host is defined else
          postgres__srv._connection.login_host
        ) | default(postgres__cfg._login_host)
      }}'
    login_password: '{{ (

          user.login_password
          if user.login_password is defined else
          postgres__srv._connection.login_password
        ) | default(omit)
      }}'
    login_port: '{{ (

          user.login_port
          if user.login_port is defined else
          postgres__srv._connection.login_port
        ) | default(postgres__cfg._port)
      }}'
    login_unix_socket: '{{ (

          user.login_unix_socket
          if user.login_unix_socket is defined else
          postgres__srv._connection.login_unix_socket
        ) | default(postgres__cfg._socket_d)
      }}'
    login_user: '{{
        (user.login_user
         if user.login_user is defined else
         postgres__srv._connection.login_user) |
        default(postgres__cfg._login_user)
      }}'
    objs: '{{ priv.objs | default(omit) }}'
    privs: '{{ priv.privs | default(omit) }}'
    roles: '{{
        priv.roles
        if priv.roles is defined else
        user.name | default(omit)
      }}'
    schema: '{{ priv.schema | default(omit) }}'
    session_role: '{{ (

          user.session_role
          if user.session_role is defined else
          postgres__srv._connection.session_role
        ) | default(omit)
      }}'
    ssl_cert: '{{ (

          user.ssl_cert
          if user.ssl_cert is defined else
          postgres__srv._connection.ssl_cert
        ) | default(omit)
      }}'
    ssl_key: '{{ (

          user.ssl_key
          if user.ssl_key is defined else
          postgres__srv._connection.ssl_key
        ) | default(omit)
      }}'
    ssl_mode: '{{ (

          user.ssl_mode
          if user.ssl_mode is defined else
          postgres__srv._connection.ssl_mode
        ) | default("prefer")
      }}'
    state: '{{ user.state | default("present") }}'
    target_roles: '{{ priv.target_roles | default(omit) }}'
    trust_input: '{{ user.trust_input | default(true) }}'
    type: '{{ priv.type | default("table") }}'
  become: true
  become_user: '{{ postgres__srv._user }}'
  loop: '{{ user.extensions.priv }}'
  loop_control:
    loop_var: 'priv'
    label:
      '{{ priv.login_db ~ " " ~ priv.type | default("") ~ " " ~ priv.privs }}'
