---
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'

- name: 'Install'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ postgres_role_packages }}'
    apt_sources: '{{ postgres_role_apt_sources }}'
    apt_package_update_cache: true

- name: 'Config'
  ansible.builtin.include_tasks: 'config.yml'
- name: 'Manage'
  ansible.builtin.include_tasks: 'manage.yml'
