---
# yamllint disable rule:line-length
collections:
  - name: 'community.general.locale_gen'  # https://docs.ansible.com/ansible/latest/collections/community/general/
  - name: 'community.postgresql'  # https://docs.ansible.com/ansible/latest/collections/community/postgresql/

roles:
  - name: 'r_pufky.srv.apt'  # https://github.com/r-pufky/ansible_collection_srv
  - name: 'r_pufky.srv.systemd'  # https://github.com/r-pufky/ansible_collection_srv
  - name: 'r_pufky.srv.users'  # https://github.com/r-pufky/ansible_collection_srv
