---
- name: 'Auto backup | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | converge | apply r_pufky.srv.postgres'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.postgres'

- name: 'Auto backup | converge | disable auto-backup'
  hosts: 'postgres-debian-12-auto_backup-disable'
  gather_facts: false
  tasks:
    - name: 'Auto backup | converge | apply r_pufky.srv.postgres'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.postgres'
      vars:
        postgres_databases_backup_enable: false
