---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.srv.postgres'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.postgres'

- name: 'Converge | disable auto-backup'
  hosts: 'postgres-debian-13-auto_backup-disable'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.srv.postgres'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.postgres'
      vars:
        postgres_cfg_databases_backup_enable: false
