---
- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | create backup directory'
      ansible.builtin.file:
        path: '/var/lib/postgres_backup'
        owner: 300
        group: 300
        mode: '0755'
        state: 'directory'

    - name: 'Prepare | set auto backup'
      ansible.builtin.copy:
        src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/skeleton.sql"
          }}'
        dest: '/var/lib/postgres_backup/skeleton.sql'
        owner: 300
        group: 300
        mode: '0640'

    - name: 'Prepare | link latest'
      ansible.builtin.file:
        src: '/var/lib/postgres_backup/skeleton.sql'
        path: '/var/lib/postgres_backup/skeleton-latest.sql'
        owner: 300
        group: 300
        mode: '0640'
        state: 'link'
