---
###############################################################################
# Postgres Handlers
###############################################################################

- name: 'Handlers | restart postgres'
  ansible.builtin.systemd:
    name: 'postgresql'
    state: 'restarted'
    daemon_reload: true
    enabled: true
