---
# yamllint disable rule:line-length
- name: 'Postgresql includes | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Postgresql includes | converge | inject include sources'
      ansible.builtin.copy:
        src: '{{ lookup("env", "MOLECULE_SCENARIO_DIRECTORY") }}/files/{{ item }}'
        dest: '/tmp/{{ item }}'
        owner: 'root'
        group: 'root'
        mode: '0644'
      loop:
        - 'if_exists.conf'
        - 'include.conf'

    - name: 'Postgresql includes | converge | apply r_pufky.srv.postgres'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.postgres'
