---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | /etc/postgresql/17/main/postgresql.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | /etc/postgresql/17/main/postgresql.conf'
        test_src: 'files/postgresql.conf'
        test_file: '/etc/postgresql/17/main/postgresql.conf'
        test_owner: 'postgres'
        test_group: 'postgres'
        test_mode: '0644'
        test_diff: true
