---
- name: 'Verify database'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name:
        'Verify config | /etc/postgresql/17/main/pg_hba.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          'Verify config | /etc/postgresql/17/main/pg_hba.conf'
        test_src: 'files/pg_hba.conf'
        test_file: '/etc/postgresql/17/main/pg_hba.conf'
        test_owner: 'postgres'
        test_group: 'postgres'
        test_mode: '0640'
        test_diff: true
