---
###############################################################################
# Default
###############################################################################
# Default values results in running service.
#
# Tests:
# * Default installation results in a running Postgres server instance.
# * Configuration files with options are rendered appropriately based on type.
# * Alternative data storage user succeeds.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        postgres_cfg_users:
          - name: 'example'
            host: 'localhost'
            password: 'example'
            state: 'present'
            append_privs: false
            encrypted: true
            extensions:
              owner:
                - login_db: 'test1'
                  obj_type: 'table'
                - login_db: 'test1'
                  obj_type: 'sequence'
                - login_db: 'test1'
                  obj_type: 'view'
              priv:
                - login_db: 'postgres'
                  privs: 'ALL'
                  type: 'database'
                - login_db: 'test1'
                  privs: 'ALL'
                  type: 'database'
        postgres_cfg_databases:
          - name: 'test1'
            owner: 'example'
          - name: 'test2'
            owner: 'postgres'
    host_vars:
      postgres-debian-13-user_data:
        posgres_srv_user_data_manage_enable: true
platforms:
  - name: 'postgres-debian-13-default'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
  - name: 'postgres-debian-13-user_data'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # systemd services.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
