---
- name: 'Verify database'
  hosts: 'all'
  gather_facts: false
  tasks:
    # community.postgresql.postgresql_user - just check user is created.
    - name: 'Verify database | query user example'
      community.postgresql.postgresql_query:
        login_db: 'postgres'
        query: 'select * from pg_catalog.pg_user where usename=%(user)s'
        named_args:
          user: 'example'
        login_host: 'localhost'
        login_unix_socket: '/var/run/postgresql'
        login_user: 'postgres'
        port: '5432'
      become: true
      become_user: 'postgres'
      register: _test_query

    - name: 'Verify database | assert user example created'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_query.rowcount == 1
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │                   example user does not exist.                    │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯

    # community.postgresql.postgresql_user - just check DB is created.
    - name: 'Verify database | query DB test1'
      community.postgresql.postgresql_query:
        login_db: 'postgres'
        query: 'select datname from pg_database where datname=%(db)s'
        named_args:
          db: 'test1'
        login_host: 'localhost'
        login_unix_socket: '/var/run/postgresql'
        login_user: 'postgres'
        port: '5432'
      become: true
      become_user: 'postgres'
      register: _test_query

    - name: 'Verify database | assert DB test1 created'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_query.rowcount == 1
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │                   roundcube DB does not exist.                    │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯

- name: 'Verify config'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify config | /etc/profile.d/postgres'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify config | /etc/profile.d/postgres'
        test_src: 'files/postgres'
        test_file: '/etc/profile.d/postgres'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

    - name:
        'Verify config | /etc/postgresql/17/scripts/postgres_owner'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          'Verify config | /etc/postgresql/17/scripts/postgres_owner'
        test_src: 'files/postgres_owner'
        test_file: '/etc/postgresql/17/scripts/postgres_owner'
        test_owner: 'postgres'
        test_group: 'postgres'
        test_mode: '0700'
        test_diff: true

    - name:
        'Verify config | /etc/postgresql/17/main'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          'Verify config | /etc/postgresql/17/main/{{ item.file }}'
        test_src: 'files/{{ item.file }}'
        test_file: '/etc/postgresql/17/main/{{ item.file }}'
        test_owner: 'postgres'
        test_group: 'postgres'
        test_mode: '{{ item.mode }}'
        test_diff: true
      loop:
        - {file: 'environment', mode: '0644'}
        - {file: 'postgresql.conf', mode: '0644'}
        - {file: 'pg_hba.conf', mode: '0640'}
        - {file: 'pg_ident.conf', mode: '0640'}
        - {file: 'pg_ctl.conf', mode: '0644'}
        - {file: 'start.conf', mode: '0644'}
      loop_control:
        label: '{{ item.file }}'
